name: deemmi
description: An App for Pet Owner
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+12

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  app_tracking_transparency: ^2.0.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.4
  dio: ^5.6.0
  dotted_border: ^2.1.0
  easy_pdf_viewer: ^1.0.8
  email_validator: ^3.0.0
  encrypt: ^5.0.1
  equatable: ^2.0.3
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^3.8.3
  fluttertoast: ^8.0.8
  get: ^4.6.5
  google_fonts: ^4.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  in_app_review: ^2.0.4
  intl: ^0.18.1
  loading_animation_widget: ^1.2.1
  open_filex: ^4.4.0
  permission_handler: ^10.4.3
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  store_redirect: ^2.0.1
  timezone: ^0.8.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  video_player: ^2.8.6
  webview_flutter: ^4.7.0

dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.2

flutter_native_splash:
  color: "#F8FAFC"
  image: "assets/icons/pettagu_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pettagu_icon.png"
  min_sdk_android: 21 # android mi

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: kanit_regular
      fonts:
        - asset: fonts/Kanit-Regular.ttf
    - family: kanit_light
      fonts:
        - asset: fonts/Kanit-Light.ttf
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - fonts/
flutter_intl:
  enabled: true